Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -21,12 +21,17 @@ jobs:
         env:
           DOCKER_USERNAME: ${{ secrets.CI_REGISTRY_USER }}
           DOCKER_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin
+        run: |
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin
+          if [ $? -ne 0 ]; then
+            echo "Docker login failed"
+            exit 1
+          fi
 
       - name: Build Docker Image
         id: build_image
         run: |
-          image_name="${{ secrets.CI_REGISTRY_IMAGE }}" # Set your image name here
+          image_name="${{ secrets.CI_REGISTRY_IMAGE }}"
           echo "Image Name: ${image_name}" # Debugging output
           if [ "${{ github.ref }}" == "refs/heads/16.0" ]; then
             tag="" # No tag for the latest version
@@ -58,13 +63,14 @@ jobs:
     if: github.ref == 'refs/heads/16.0'
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Login to Docker Registry
         env:
           DOCKER_USERNAME: ${{ secrets.CI_REGISTRY_USER }}
           DOCKER_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin
+        run: |
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin
 
       - name: Pull Docker Image
         run: |
@@ -76,6 +82,8 @@ jobs:
       - name: Deploy with Docker Compose
         run: |
           cd /opt/deployments/erp-stage
+          COMPOSE_HTTP_TIMEOUT=200 docker-compose pull            # Pull latest images
+          COMPOSE_HTTP_TIMEOUT=200 docker-compose build           # Rebuild services if necessary
           COMPOSE_HTTP_TIMEOUT=200 docker-compose up -d --scale stage_web="${{ secrets.SCALE_NUMBER_STAGE }}"
           docker image prune -f --filter label=system
           docker volume prune -f 
@@ -86,13 +94,14 @@ jobs:
     if: github.ref == 'refs/heads/16.0'
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Login to Docker Registry
         env:
           DOCKER_USERNAME: ${{ secrets.CI_REGISTRY_USER }}
           DOCKER_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin
+        run: |
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin
 
       - name: Pull Docker Image
         run: |
@@ -104,6 +113,8 @@ jobs:
       - name: Deploy with Docker Compose
         run: |
           cd /opt/deployments/erp
+          COMPOSE_HTTP_TIMEOUT=200 docker-compose pull            # Pull latest images
+          COMPOSE_HTTP_TIMEOUT=200 docker-compose build           # Rebuild services if necessary
           COMPOSE_HTTP_TIMEOUT=200 docker-compose up -d --scale web="${{ secrets.SCALE_NUMBER }}"
           docker image prune -f --filter label=system
           docker volume prune -f 
